sudo: false
dist: trusty

cache: bundler

before: &before
  - uname -a
  - free -m
  - df -h
  - ulimit -a
 
show: &show
  - bundle show

jobs:
  include:
    - stage: prepare cache
      script: true
      rvm: 2.3
    - stage: test
      before_script:
        - *before
        - export FOO='foo'
      script:
        - *show
        - echo $FOO
      rvm: 2.3
      addons:
        apt:
          packages:
          - clang-3.6      
    - stage: test
      before_script:
        - *before
        - export FOO='oof'
      script:
        - *show
        - echo $FOO
      rvm: 2.3
      addons:
        apt:
          packages:
          - gfortran
    - stage: test
      script: bundle show
      rvm: 2.3
