sudo: false
dist: trusty

cache: bundler

test: &test
  stage: test
  before_script:
    - uname -a
    - free -m
    - df -h
    - ulimit -a 
  script:
    - bundle show

jobs:
  include:
    - stage: prepare cache
      script: true
      rvm: 2.3
    - <<: *test
      before_script:
        - export FOO='foo'
      script:
        - echo $FOO
      rvm: 2.3
      addons:
        apt:
          packages:
          - clang-3.6      
    - <<: *test
      before_script:
        - export FOO='oof'
      script: 
        - echo $FOO
      rvm: 2.3
      addons:
        apt:
          packages:
          - gfortran
    - stage: test
      script: bundle show
      rvm: 2.3
