sudo: false
dist: trusty

cache: bundler

jobs:
  include:
    - stage: prepare cache
      script: true
      rvm: 2.3
    - stage: test
      script: bundle show
      rvm: 2.3
      env:
        - FOO='foo'
    - stage: test
      script: bundle show
      rvm: 2.3
      env:
        - FOO='oof'
    - stage: test
      script: bundle show
      rvm: 2.3
