sudo: false
dist: trusty

cache: bundler

jobs:
  include:
    - stage: prepare cache
      script: true
      rvm: 2.3
    - stage: test
      script: bundle show
      rvm: 2.3
      addons:
        apt:
          packages:
          - clang-3.6      
    - stage: test
      script: bundle show
      rvm: 2.3
      addons:
        apt:
          packages:
          - gfortran
    - stage: test
      script: bundle show
      rvm: 2.3
