sudo: false
dist: trusty

cache: bundler

jobs:
  include:
    - stage: prepare cache
      script: true
      rvm: 2.3
    - stage: test
      before_script:
        - export FOO='foo'
      script:
        - echo $FOO
        - bundle show
      rvm: 2.3
      addons:
        apt:
          packages:
          - clang-3.6      
    - stage: test
      before_script:
        - export FOO='oof'
      script: 
        - echo $FOO
        - bundle show
      rvm: 2.3
      addons:
        apt:
          packages:
          - gfortran
    - stage: test
      script: bundle show
      rvm: 2.3
